config/routes.rb
Rails.application.routes.draw do
  resources :fees

  resources :exams

  resources :teachers

  resources :takes

  resources :enrolls

  resources :classses

  resources :students

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'
  get 'users/index'
  resources :users
	root :to => 'user_sessions#new'
	resources :user_sessions
	resources :users

	get 'login' => 'user_sessions#new', :as => :login
	post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :father_name, :CINC, :qualification, :joining_date, :gender, :religion, :contact, :address)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :father_name %><br>
    <%= f.text_field :father_name %>
  </div>
  <div class="field">
    <%= f.label :CINC %><br>
    <%= f.text_field :CINC %>
  </div>
  <div class="field">
    <%= f.label :qualification %><br>
    <%= f.text_field :qualification %>
  </div>
  <div class="field">
    <%= f.label :joining_date %><br>
    <%= f.date_select :joining_date %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :religion %><br>
    <%= f.text_field :religion %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<div align="center">
<h1>Editing Teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>
<div/>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Teachers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Father name</th>
      <th>Cinc</th>
      <th>Qualification</th>
      <th>Joining date</th>
      <th>Gender</th>
      <th>Religion</th>
      <th>Contact</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.father_name %></td>
        <td><%= teacher.CINC %></td>
        <td><%= teacher.qualification %></td>
        <td><%= teacher.joining_date %></td>
        <td><%= teacher.gender %></td>
        <td><%= teacher.religion %></td>
        <td><%= teacher.contact %></td>
        <td><%= teacher.address %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>
<%= link_to 'Back', users_path %>

app/views/teachers/new.html.erb
<div align="center">
<h1>New Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>
<div/>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Father name:</strong>
  <%= @teacher.father_name %>
</p>

<p>
  <strong>Cinc:</strong>
  <%= @teacher.CINC %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @teacher.qualification %>
</p>

<p>
  <strong>Joining date:</strong>
  <%= @teacher.joining_date %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @teacher.gender %>
</p>

<p>
  <strong>Religion:</strong>
  <%= @teacher.religion %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @teacher.contact %>
</p>

<p>
  <strong>Address:</strong>
  <%= @teacher.address %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>