config/routes.rb
Rails.application.routes.draw do
  resources :fees

  resources :exams

  resources :teachers

  resources :takes

  resources :enrolls

  resources :classses

  resources :students

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'
  get 'users/index'
  resources :users
	root :to => 'user_sessions#new'
	resources :user_sessions
	resources :users

	get 'login' => 'user_sessions#new', :as => :login
	post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/fee.rb
class Fee < ActiveRecord::Base
end

app/controllers/fees_controller.rb
class FeesController < ApplicationController
  before_action :set_fee, only: [:show, :edit, :update, :destroy]

  # GET /fees
  # GET /fees.json
  def index
    @fees = Fee.all
  end

  # GET /fees/1
  # GET /fees/1.json
  def show
  end

  # GET /fees/new
  def new
    @fee = Fee.new
  end

  # GET /fees/1/edit
  def edit
  end

  # POST /fees
  # POST /fees.json
  def create
    @fee = Fee.new(fee_params)

    respond_to do |format|
      if @fee.save
        format.html { redirect_to @fee, notice: 'Fee was successfully created.' }
        format.json { render :show, status: :created, location: @fee }
      else
        format.html { render :new }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fees/1
  # PATCH/PUT /fees/1.json
  def update
    respond_to do |format|
      if @fee.update(fee_params)
        format.html { redirect_to @fee, notice: 'Fee was successfully updated.' }
        format.json { render :show, status: :ok, location: @fee }
      else
        format.html { render :edit }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fees/1
  # DELETE /fees/1.json
  def destroy
    @fee.destroy
    respond_to do |format|
      format.html { redirect_to fees_url, notice: 'Fee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fee
      @fee = Fee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fee_params
      params.require(:fee).permit(:fdate, :amount)
    end
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/views/fees/_form.html.erb
<%= form_for(@fee) do |f| %>
  <% if @fee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fee.errors.count, "error") %> prohibited this fee from being saved:</h2>

      <ul>
      <% @fee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fdate %><br>
    <%= f.date_select :fdate %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fees/edit.html.erb
<div align="center">
<h1>Editing Fee</h1>

<%= render 'form' %>

<%= link_to 'Show', @fee %> |
<%= link_to 'Back', fees_path %>
<div/>

app/views/fees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fees</h1>

<table>
  <thead>
    <tr>
      <th>Fdate</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fees.each do |fee| %>
      <tr>
        <td><%= fee.fdate %></td>
        <td><%= fee.amount %></td>
        <td><%= link_to 'Show', fee %></td>
        <td><%= link_to 'Edit', edit_fee_path(fee) %></td>
        <td><%= link_to 'Destroy', fee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fee', new_fee_path %>
<%= link_to 'Back', users_path %>

app/views/fees/new.html.erb
<div align="center">
<h1>New Fee</h1>

<%= render 'form' %>

<%= link_to 'Back', fees_path %>
<div/>

app/views/fees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fdate:</strong>
  <%= @fee.fdate %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @fee.amount %>
</p>

<%= link_to 'Edit', edit_fee_path(@fee) %> |
<%= link_to 'Back', fees_path %>